import { connectMongoDB } from '@/lib/mongodb';
import Events from '@/models/events';
import { authenticate } from '@/lib/authenticate';
import { logger } from '@/lib/logger';

// Helper function to download image from URL
async function downloadImage(url) {
  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to fetch image: ${response.statusText}`);
    }
    const arrayBuffer = await response.arrayBuffer();
    return Buffer.from(arrayBuffer);
  } catch (error) {
    console.warn(`Failed to download image from ${url}:`, error);
    return null;
  }
}

export async function POST(req) {
  let doc = null;
  let user = null;
  const ACTION = 'Generate PDF';

  try {
    const { eventId } = await req.json();
    user = await authenticate(req);
    if (!user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
      });
    }

    await connectMongoDB();
    const eventData = await Events.findById(eventId);
    if (!eventData) {
      return new Response(JSON.stringify({ error: 'Event not found' }), {
        status: 404,
      });
    }

    // Dynamically import pdfkit to avoid webpack bundling issues with font files
    const PDFDocument = (await import('pdfkit')).default;

    // Create PDF document
    doc = new PDFDocument({
      size: 'A4',
      margins: { top: 36, bottom: 36, left: 36, right: 36 }, // 0.5in = 36pt
    });

    // Collect PDF data in a buffer
    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => {}); // Buffer collection handled by promise

    const pdfBufferPromise = new Promise((resolve, reject) => {
      doc.on('end', () => {
        resolve(Buffer.concat(chunks));
      });
      doc.on('error', reject);
    });

    // Helper function to add heading
    function addHeading(text, y, level = 2) {
      const fontSize = level === 1 ? 16 : level === 2 ? 13 : 12;
      doc.fontSize(fontSize);
      doc.fillColor('#2c3e50');
      doc.font('Helvetica-Bold');
      const height = doc.heightOfString(text);
      doc.text(text, doc.page.margins.left, y, {
        align: level === 1 ? 'center' : 'left',
      });
      return height + 8;
    }

    // Track page count for footer
    let pageCount = 1;

    // Add footer to current page
    const addFooter = () => {
      const footerY = doc.page.height - doc.page.margins.bottom - 20;
      doc.fontSize(9);
      doc.fillColor('#95a5a6');
      doc.font('Helvetica');
      doc.text(
        `Generated by Eventify • ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}`,
        doc.page.margins.left,
        footerY,
        { align: 'right' }
      );
    };

    // Add footer when new page is added
    doc.on('pageAdded', () => {
      // Add footer to previous page before switching
      if (pageCount > 1) {
        doc.switchToPage(pageCount - 2);
        addFooter();
        doc.switchToPage(pageCount - 1);
      }
      pageCount++;
    });

    let yPosition = doc.page.margins.top;

    // Header Logo
    const logoUrl =
      eventData.college === 'SIT'
        ? 'https://eventifys3.s3.ap-south-1.amazonaws.com/SIT+WORDING+1.png'
        : eventData.college === 'SEC'
          ? 'https://eventifys3.s3.ap-south-1.amazonaws.com/SEC+LOGO.png'
          : 'https://eventifys3.s3.ap-south-1.amazonaws.com/SEC+and+SIT+WORDING+1.png';

    const logoBuffer = await downloadImage(logoUrl);
    if (logoBuffer) {
      try {
        doc.image(
          logoBuffer,
          doc.page.margins.left +
            (doc.page.width - doc.page.margins.left - doc.page.margins.right) /
              2 -
            150,
          yPosition,
          {
            fit: [300, 100],
            align: 'center',
          }
        );
        yPosition += 120;
      } catch (err) {
        console.warn('Failed to add logo:', err);
        yPosition += 20;
      }
    } else {
      yPosition += 20;
    }

    // Title
    yPosition += addHeading(
      `Event Report: ${eventData.eventData.EventName}`,
      yPosition,
      1
    );
    yPosition += 10;

    // Event Info (two columns)
    const infoLeft = doc.page.margins.left;
    const infoRight = doc.page.width / 2 + 20;
    const infoWidth =
      (doc.page.width - doc.page.margins.left - doc.page.margins.right) / 2 -
      20;
    let infoY = yPosition;

    const eventInfo = [
      ['Event ID:', eventData.ins_id || 'N/A'],
      ['Department:', eventData.dept],
      ['Venue:', eventData.eventData.EventVenue],
      ['Duration:', `${eventData.eventData.EventDuration} hours`],
      [
        'Start:',
        new Date(eventData.eventData.StartTime).toLocaleString('en-IN', {
          timeZone: 'Asia/Kolkata',
        }),
      ],
      [
        'End:',
        new Date(eventData.eventData.EndTime).toLocaleString('en-IN', {
          timeZone: 'Asia/Kolkata',
        }),
      ],
    ];

    eventInfo.forEach(([label, value], index) => {
      const x = index % 2 === 0 ? infoLeft : infoRight;
      const y = infoY + Math.floor(index / 2) * 20;

      doc.fontSize(11);
      doc.fillColor('#2c3e50');
      doc.font('Helvetica-Bold');
      doc.text(label, x, y);
      doc.font('Helvetica');
      doc.text(value, x + 80, y);
    });

    yPosition = infoY + Math.ceil(eventInfo.length / 2) * 20 + 15;

    // Event Objective
    yPosition += addHeading('Event Objective', yPosition);
    doc.fontSize(11);
    doc.fillColor('#2c3e50');
    doc.font('Helvetica');
    const objectiveHeight = doc.heightOfString(
      eventData.eventData.EventObjective,
      {
        width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
      }
    );
    doc.text(
      eventData.eventData.EventObjective,
      doc.page.margins.left,
      yPosition,
      {
        width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
      }
    );
    yPosition += objectiveHeight + 15;

    // Stakeholders
    yPosition += addHeading('Stakeholders', yPosition);
    if (
      eventData.eventData.eventStakeholders &&
      eventData.eventData.eventStakeholders.length > 0
    ) {
      eventData.eventData.eventStakeholders.forEach(stakeholder => {
        doc.fontSize(11);
        doc.fillColor('#2c3e50');
        doc.font('Helvetica');
        doc.text(`• ${stakeholder}`, doc.page.margins.left + 20, yPosition);
        yPosition += 15;
      });
    } else {
      doc.text('N/A', doc.page.margins.left + 20, yPosition);
      yPosition += 15;
    }
    yPosition += 5;

    // Event Coordinators
    yPosition += addHeading('Event Coordinators', yPosition);
    if (
      eventData.eventData.eventCoordinators &&
      eventData.eventData.eventCoordinators.length > 0
    ) {
      eventData.eventData.eventCoordinators.forEach(coordinator => {
        // Check if we need a new page
        if (yPosition > doc.page.height - doc.page.margins.bottom - 100) {
          doc.addPage();
          yPosition = doc.page.margins.top;
        }

        const coordX = doc.page.margins.left;
        const coordY = yPosition;

        // No border - removed doc.rect line
        doc.fontSize(11);
        doc.fillColor('#2c3e50');
        doc.font('Helvetica-Bold');
        doc.text(
          `${coordinator.coordinatorName} (${coordinator.coordinatorRole})`,
          coordX,
          coordY
        );
        doc.font('Helvetica');
        doc.text(coordinator.coordinatorMail, coordX, coordY + 15);
        doc.text(coordinator.coordinatorPhone, coordX, coordY + 30);

        // Move to next coordinator position (one below)
        yPosition += 50;
      });
      yPosition += 10;
    } else {
      doc.text('N/A', doc.page.margins.left, yPosition);
      yPosition += 15;
    }

    // Resource Persons
    if (
      eventData.eventData.eventResourcePerson &&
      eventData.eventData.eventResourcePerson.length > 0
    ) {
      yPosition += addHeading('Resource Persons', yPosition);
      eventData.eventData.eventResourcePerson.forEach(person => {
        if (yPosition > doc.page.height - doc.page.margins.bottom - 100) {
          doc.addPage();
          yPosition = doc.page.margins.top;
        }

        const personX = doc.page.margins.left;
        const personY = yPosition;

        // No border - removed doc.rect line
        doc.fontSize(11);
        doc.fillColor('#2c3e50');
        doc.font('Helvetica-Bold');
        doc.text(
          `${person.ResourcePersonName} (${person.ResourcePersonDesgn})`,
          personX,
          personY
        );
        doc.font('Helvetica');
        doc.text(person.ResourcePersonMail, personX, personY + 15);
        doc.text(person.ResourcePersonPhone, personX, personY + 30);
        const addressHeight = doc.heightOfString(person.ResourcePersonAddr, {
          width:
            doc.page.width - doc.page.margins.left - doc.page.margins.right,
        });
        doc.text(person.ResourcePersonAddr, personX, personY + 45, {
          width:
            doc.page.width - doc.page.margins.left - doc.page.margins.right,
        });

        // Move to next resource person position (one below)
        yPosition += 60 + addressHeight;
      });
      yPosition += 10;
    }

    // Budget
    if (eventData.eventData.Budget) {
      yPosition += addHeading('Budget Information', yPosition);
      doc.fontSize(11);
      doc.fillColor('#2c3e50');
      doc.font('Helvetica-Bold');
      doc.text('Budget: ', doc.page.margins.left, yPosition);
      doc.font('Helvetica');
      doc.text(
        `₹${eventData.eventData.Budget}`,
        doc.page.margins.left + 60,
        yPosition
      );
      yPosition += 20;
    }

    // Event Poster
    if (
      eventData.eventData.fileUrl?.poster &&
      /\.(png|jpe?g)$/i.test(eventData.eventData.fileUrl.poster)
    ) {
      yPosition += addHeading('Event Poster', yPosition);
      const posterBuffer = await downloadImage(
        eventData.eventData.fileUrl.poster
      );
      if (posterBuffer) {
        try {
          if (yPosition > doc.page.height - doc.page.margins.bottom - 200) {
            doc.addPage();
            yPosition = doc.page.margins.top;
          }
          doc.image(
            posterBuffer,
            doc.page.margins.left +
              (doc.page.width -
                doc.page.margins.left -
                doc.page.margins.right) /
                2 -
              200,
            yPosition,
            {
              fit: [400, 200],
              align: 'center',
            }
          );
          yPosition += 220;
        } catch (err) {
          console.warn('Failed to add poster:', err);
          yPosition += 20;
        }
      }
    }

    // Post Event Documentation
    if (eventData.postEventData) {
      yPosition += addHeading('Post Event Documentation', yPosition);

      // Event Photos
      if (
        eventData.postEventData.fileUrl?.geoPhotos &&
        eventData.postEventData.fileUrl.geoPhotos.length > 0
      ) {
        yPosition += addHeading('Event Photos', yPosition, 3);
        for (const photoUrl of eventData.postEventData.fileUrl.geoPhotos) {
          if (yPosition > doc.page.height - doc.page.margins.bottom - 200) {
            doc.addPage();
            yPosition = doc.page.margins.top;
          }
          const photoBuffer = await downloadImage(photoUrl);
          if (photoBuffer) {
            try {
              doc.image(
                photoBuffer,
                doc.page.margins.left +
                  (doc.page.width -
                    doc.page.margins.left -
                    doc.page.margins.right) /
                    2 -
                  200,
                yPosition,
                {
                  fit: [400, 200],
                  align: 'center',
                }
              );
              yPosition += 220;
            } catch (err) {
              console.warn('Failed to add photo:', err);
            }
          }
        }
      }

      // Report and Financial Documents (as text links)
      if (eventData.postEventData.fileUrl?.report) {
        doc.fontSize(11);
        doc.fillColor('#2c3e50');
        doc.font('Helvetica-Bold');
        doc.text('Report: ', doc.page.margins.left, yPosition);
        doc.font('Helvetica');
        doc.fillColor('#0066cc');
        doc.text(
          eventData.postEventData.fileUrl.report,
          doc.page.margins.left + 50,
          yPosition,
          {
            link: eventData.postEventData.fileUrl.report,
          }
        );
        yPosition += 50;
      }

      if (eventData.postEventData.fileUrl?.financialCommitments) {
        doc.fontSize(11);
        doc.fillColor('#2c3e50');
        doc.font('Helvetica-Bold');
        doc.text('Financial Documents: ', doc.page.margins.left, yPosition);
        doc.font('Helvetica');
        doc.fillColor('#0066cc');
        doc.text(
          eventData.postEventData.fileUrl.financialCommitments,
          doc.page.margins.left + 130,
          yPosition,
          {
            link: eventData.postEventData.fileUrl.financialCommitments,
          }
        );
        yPosition += 20;
      }
    }

    // Add footer to last page
    addFooter();

    // Finalize PDF
    doc.end();
    const pdfBuffer = await pdfBufferPromise;

    await logger(
      user._id,
      ACTION,
      `PDF Generated Successfully - Event: ${eventData.eventData.EventName}`,
      200
    );

    return new Response(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${eventData.eventData.EventName}.pdf"`,
      },
    });
  } catch (error) {
    console.error('PDF Generation Error:', error);

    // Cleanup resources in case of error
    if (doc) {
      try {
        doc.end();
      } catch (err) {
        console.warn('Error closing PDF document during cleanup:', err);
      }
    }

    await logger(
      user?._id || 'UNKNOWN',
      ACTION,
      'PDF Generation Failed: ' + error.message,
      500
    );

    return new Response(JSON.stringify({ error: 'Failed to generate PDF' }), {
      status: 500,
    });
  }
}
